#!/bin/sh
set -e
set -u
export DEBIAN_FRONTEND=noninteractive
n=0
max=2
until [ $n -gt $max ]; do
  set +e
  (
    apt-get update -qq &&
    apt-get install -y --no-install-recommends "$@"
  )
  CODE=$?
  set -e
  if [ $CODE -eq 0 ]; then
    break
  fi
  if [ $n -eq $max ]; then
    exit $CODE
  fi
  echo "apt failed, retrying"
  n=$(($n + 1))
done
rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
c_rehash
