name: docker-buildx-push

on:
  push:
    branches:
      - master

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout master
        uses: actions/checkout@master
      -
        name: Build and publish image
        uses: zmingxie/docker_buildx@master
        with:
          publish: false
          imageName: test
          dockerHubUser: YOUR_USER_HERE
          dockerHubPassword: YOUR_PASSWORD_HERE
